// The named looks. Each is a starting point: pick the one closest to the brief, then makeTheme() it to the
// brand. The styles catalogue in the skill says which components and motion each look pairs with.
import type {ThemeSpec} from './theme';

const motion = (m: Partial<ThemeSpec['motion']> = {}): ThemeSpec['motion'] => ({
	enter: 'rise',
	enterFrames: 18,
	exitFrames: 14,
	stagger: 5,
	distance: 28,
	curve: 'out',
	spring: 'calm',
	...m,
});

const THEME_LIST = [
	{
		name: 'studio',
		description: 'Clean light explainer and product look: off-white stage, near-black type, one blue accent',
		dark: false,
		colors: {bg: '#F5F6F7', bg2: '#FFFFFF', surface: '#FFFFFF', text: '#111827', muted: '#686F7D', faint: '#D1D5DB', line: '#E5E7EB', accent: '#2563EB', accentText: '#2563EB', accent2: '#F59E0B', highlight: '#FDE68A', positive: '#16A34A', negative: '#DC2626', onAccent: '#FFFFFF'},
		fonts: {display: 'Inter', body: 'Inter', mono: 'JetBrainsMono', bangla: 'AnekBangla'},
		weights: {display: 800, body: 500, strong: 700},
		tracking: {display: -0.035, caps: 0.08},
		caps: false,
		radius: 24,
		motion: motion(),
		texture: {grain: 0, vignette: 0, grainRate: 6},
	},
	{
		name: 'midnight',
		description: 'Dark SaaS and app launch: deep blue-black ground, cool blue and mint accents',
		dark: true,
		colors: {bg: '#0B0D12', bg2: '#12151C', surface: '#171B24', text: '#F3F5F9', muted: '#9AA3B2', faint: '#3A4150', line: '#262C37', accent: '#5B8CFF', accentText: '#5B8CFF', accent2: '#3DDC97', highlight: '#FFD166', positive: '#3DDC97', negative: '#FF5C5C', onAccent: '#0B0D12'},
		fonts: {display: 'Manrope', body: 'Inter', mono: 'JetBrainsMono', bangla: 'AnekBangla'},
		weights: {display: 800, body: 500, strong: 700},
		tracking: {display: -0.035, caps: 0.1},
		caps: false,
		radius: 20,
		motion: motion({enterFrames: 16, exitFrames: 12, stagger: 4, distance: 24, spring: 'settle'}),
		texture: {grain: 0.03, vignette: 0.25, grainRate: 6},
	},
	{
		name: 'keynote',
		description: 'Keynote minimal, dark: huge quiet type, slow blur-in, lots of black',
		dark: true,
		colors: {bg: '#0A0A0B', bg2: '#141416', surface: '#1C1C1F', text: '#F5F5F7', muted: '#86868B', faint: '#3A3A3C', line: '#2C2C2E', accent: '#2997FF', accentText: '#2997FF', accent2: '#FF9F0A', highlight: '#FFD60A', positive: '#30D158', negative: '#FF453A', onAccent: '#0B0B0C'},
		fonts: {display: 'Inter', body: 'Inter', mono: 'JetBrainsMono', bangla: 'AnekBangla'},
		weights: {display: 700, body: 400, strong: 600},
		tracking: {display: -0.045, caps: 0.06},
		caps: false,
		radius: 28,
		motion: motion({enter: 'blur', enterFrames: 24, exitFrames: 18, stagger: 6, distance: 16, curve: 'outQuart'}),
		texture: {grain: 0, vignette: 0, grainRate: 6},
	},
	{
		name: 'keynoteLight',
		description: 'Keynote minimal, light: white stage, graphite type, one blue',
		dark: false,
		colors: {bg: '#FBFBFD', bg2: '#F5F5F7', surface: '#FFFFFF', text: '#1D1D1F', muted: '#6E6E73', faint: '#D2D2D7', line: '#E5E5EA', accent: '#0071E3', accentText: '#0071E3', accent2: '#FF9500', highlight: '#FFE17A', positive: '#248A3D', negative: '#D70015', onAccent: '#FFFFFF'},
		fonts: {display: 'Inter', body: 'Inter', mono: 'JetBrainsMono', bangla: 'AnekBangla'},
		weights: {display: 700, body: 400, strong: 600},
		tracking: {display: -0.045, caps: 0.06},
		caps: false,
		radius: 28,
		motion: motion({enter: 'blur', enterFrames: 24, exitFrames: 18, stagger: 6, distance: 16, curve: 'outQuart'}),
		texture: {grain: 0, vignette: 0, grainRate: 6},
	},
	{
		name: 'vox',
		description: 'Vox-style collage explainer: warm grey paper with grain, orange accent, red marker, bold sans',
		dark: false,
		colors: {bg: '#D9D7D1', bg2: '#E6E3DC', surface: '#F9F5ED', text: '#1C1B19', muted: '#5E5A52', faint: '#B5B1A8', line: '#BDB9B0', accent: '#FF8900', accentText: '#A73700', accent2: '#E04329', highlight: '#F4B41A', positive: '#2E7D32', negative: '#C62828', onAccent: '#1C1B19'},
		fonts: {display: 'Montserrat', body: 'Inter', mono: 'SpecialElite', bangla: 'AnekBangla', serif: 'Merriweather', hand: 'Bangers'},
		weights: {display: 900, body: 600, strong: 800},
		tracking: {display: -0.02, caps: 0.06},
		caps: false,
		radius: 24,
		motion: motion({enterFrames: 13, exitFrames: 10, stagger: 6, distance: 60}),
		texture: {grain: 0.16, vignette: 0.3, grainRate: 3},
	},
	{
		name: 'editorial',
		description: 'Magazine editorial: white page, large serif headlines, editorial red, masked reveals',
		dark: false,
		colors: {bg: '#FFFFFF', bg2: '#F4F4F4', surface: '#F4F4F4', text: '#111111', muted: '#6B6B6B', faint: '#CFCFCF', line: '#E3E3E3', accent: '#D7263D', accentText: '#D7263D', accent2: '#1F4E79', highlight: '#FFE3A3', positive: '#2E7D32', negative: '#D7263D', onAccent: '#FFFFFF'},
		fonts: {display: 'InstrumentSerif', body: 'Inter', mono: 'IBMPlexMono', bangla: 'TiroBangla', serif: 'InstrumentSerif'},
		weights: {display: 400, body: 500, strong: 700},
		tracking: {display: -0.02, caps: 0.12},
		caps: false,
		radius: 4,
		motion: motion({enter: 'mask', enterFrames: 20, exitFrames: 14, stagger: 4, distance: 0}),
		texture: {grain: 0.02, vignette: 0, grainRate: 6},
	},
	{
		name: 'kinetic',
		description: 'Kinetic type promo: black, white condensed capitals, acid accent, fast masked hits',
		dark: true,
		colors: {bg: '#0A0A0A', bg2: '#161616', surface: '#1E1E1E', text: '#FFFFFF', muted: '#A3A3A3', faint: '#404040', line: '#2A2A2A', accent: '#E8FF3A', accentText: '#E8FF3A', accent2: '#FF3D00', highlight: '#E8FF3A', positive: '#4ADE80', negative: '#FF3D00', onAccent: '#0A0A0A'},
		fonts: {display: 'Anton', body: 'Inter', mono: 'JetBrainsMono', bangla: 'AnekBangla'},
		weights: {display: 400, body: 600, strong: 800},
		tracking: {display: 0, caps: 0.02},
		caps: true,
		radius: 0,
		motion: motion({enter: 'mask', enterFrames: 10, exitFrames: 8, stagger: 3, distance: 40, curve: 'snap', spring: 'snappy'}),
		texture: {grain: 0.05, vignette: 0, grainRate: 8},
	},
	{
		name: 'swiss',
		description: 'Swiss grid: white, black, one red, flush-left grotesk, hard wipes on a grid',
		dark: false,
		colors: {bg: '#FFFFFF', bg2: '#F2F2F2', surface: '#FFFFFF', text: '#0A0A0A', muted: '#6F6F6F', faint: '#CFCFCF', line: '#0A0A0A', accent: '#E30613', accentText: '#E30613', accent2: '#0A0A0A', highlight: '#FFE500', positive: '#008A3E', negative: '#E30613', onAccent: '#FFFFFF'},
		fonts: {display: 'Archivo', body: 'Archivo', mono: 'IBMPlexMono', bangla: 'AnekBangla'},
		weights: {display: 800, body: 500, strong: 700},
		tracking: {display: -0.04, caps: 0.04},
		caps: false,
		radius: 0,
		motion: motion({enter: 'wipe', enterFrames: 16, exitFrames: 12, stagger: 4, distance: 0, curve: 'inOut'}),
		texture: {grain: 0, vignette: 0, grainRate: 6},
	},
	{
		name: 'neon',
		description: 'Neon night: ink-blue ground, cyan and magenta light, glow, wide display type',
		dark: true,
		colors: {bg: '#07091A', bg2: '#0E1233', surface: '#131847', text: '#EAF2FF', muted: '#8C9CC8', faint: '#2B3470', line: '#1E2560', accent: '#00E5FF', accentText: '#00E5FF', accent2: '#FF2BD6', highlight: '#FFE600', positive: '#39FF88', negative: '#FF3B6B', onAccent: '#07091A'},
		fonts: {display: 'Unbounded', body: 'SpaceGrotesk', mono: 'JetBrainsMono', bangla: 'AnekBangla'},
		weights: {display: 700, body: 500, strong: 700},
		tracking: {display: -0.02, caps: 0.12},
		caps: false,
		radius: 16,
		motion: motion({enter: 'blur', enterFrames: 16, exitFrames: 12, stagger: 4, distance: 20}),
		texture: {grain: 0.04, vignette: 0.4, grainRate: 6},
	},
	{
		name: 'retro',
		description: 'Eighties retro: purple night, hot pink and cyan, chunky mono display, stepped motion',
		dark: true,
		colors: {bg: '#1A0F2E', bg2: '#2A1747', surface: '#33205A', text: '#FFE9D6', muted: '#C7A9D9', faint: '#5A3D7A', line: '#4A2F6A', accent: '#FF5E8A', accentText: '#FF5E8A', accent2: '#3DE0F5', highlight: '#FFC857', positive: '#7CFFB2', negative: '#FF5E5E', onAccent: '#1A0F2E'},
		fonts: {display: 'RubikMonoOne', body: 'SpaceGrotesk', mono: 'VT323', bangla: 'AnekBangla'},
		weights: {display: 400, body: 500, strong: 700},
		tracking: {display: 0, caps: 0.06},
		caps: true,
		radius: 8,
		motion: motion({enter: 'pop', enterFrames: 12, exitFrames: 10, stagger: 4, distance: 30, curve: 'outBack', spring: 'pop'}),
		texture: {grain: 0.12, vignette: 0.45, grainRate: 12},
	},
	{
		name: 'corporate',
		description: 'Corporate and finance: cool grey page, navy type, teal accent, calm motion',
		dark: false,
		colors: {bg: '#F4F6F9', bg2: '#FFFFFF', surface: '#FFFFFF', text: '#0F1B2D', muted: '#5B6B7F', faint: '#C9D2DE', line: '#DDE3EA', accent: '#0E7C86', accentText: '#0E7C86', accent2: '#1F4E8C', highlight: '#FFE08A', positive: '#1E8E3E', negative: '#C5221F', onAccent: '#FFFFFF'},
		fonts: {display: 'IBMPlexSans', body: 'IBMPlexSans', mono: 'IBMPlexMono', bangla: 'NotoSansBengali'},
		weights: {display: 700, body: 400, strong: 600},
		tracking: {display: -0.025, caps: 0.1},
		caps: false,
		radius: 12,
		motion: motion({enterFrames: 20, distance: 20, curve: 'outCubic'}),
		texture: {grain: 0, vignette: 0, grainRate: 6},
	},
	{
		name: 'playful',
		description: 'Flat illustrated explainer: sky blue, coral and sun yellow, rounded type, bouncy pops',
		dark: false,
		colors: {bg: '#DFF4FF', bg2: '#BFE6FF', surface: '#FFFFFF', text: '#1B2A41', muted: '#4A5D7A', faint: '#A9C7DD', line: '#9CC9E8', accent: '#FF6B6B', accentText: '#C8373E', accent2: '#FFC93C', highlight: '#FFE66D', positive: '#2BB673', negative: '#E63946', onAccent: '#111111'},
		fonts: {display: 'BalooDa2', body: 'Nunito', mono: 'JetBrainsMono', bangla: 'BalooDa2'},
		weights: {display: 800, body: 700, strong: 800},
		tracking: {display: -0.01, caps: 0.06},
		caps: false,
		radius: 28,
		motion: motion({enter: 'pop', enterFrames: 14, exitFrames: 10, stagger: 4, distance: 40, curve: 'outBack', spring: 'bouncy'}),
		texture: {grain: 0, vignette: 0, grainRate: 6},
	},
	{
		name: 'whiteboard',
		description: 'Whiteboard and sketch: white board, marker black, blue and red markers, hand lettering',
		dark: false,
		colors: {bg: '#FFFFFF', bg2: '#F6F6F4', surface: '#FFFFFF', text: '#1A1A1A', muted: '#555555', faint: '#CCCCCC', line: '#1A1A1A', accent: '#1E5AFF', accentText: '#1E5AFF', accent2: '#E4312B', highlight: '#FFE45C', positive: '#1B998B', negative: '#E4312B', onAccent: '#FFFFFF'},
		fonts: {display: 'PermanentMarker', body: 'PatrickHand', mono: 'Inconsolata', bangla: 'Atma', hand: 'Caveat'},
		weights: {display: 400, body: 400, strong: 700},
		tracking: {display: 0, caps: 0.04},
		caps: false,
		radius: 6,
		motion: motion({enter: 'fade', enterFrames: 16, exitFrames: 12, stagger: 6, distance: 0, curve: 'outCubic'}),
		texture: {grain: 0.02, vignette: 0, grainRate: 6},
	},
	{
		name: 'luxury',
		description: 'Luxury and fashion: warm black, gold, spaced serif capitals, slow blur and long holds',
		dark: true,
		colors: {bg: '#0C0B0A', bg2: '#15130F', surface: '#1B1814', text: '#F2EDE4', muted: '#A39B8E', faint: '#4A443B', line: '#2E2923', accent: '#C9A45C', accentText: '#C9A45C', accent2: '#8C6A3F', highlight: '#E6CF9A', positive: '#8FBF8A', negative: '#C26A5A', onAccent: '#0C0B0A'},
		fonts: {display: 'CormorantGaramond', body: 'Manrope', mono: 'IBMPlexMono', bangla: 'TiroBangla', serif: 'CormorantGaramond'},
		weights: {display: 500, body: 400, strong: 600},
		tracking: {display: 0.02, caps: 0.18},
		caps: true,
		radius: 2,
		motion: motion({enter: 'blur', enterFrames: 30, exitFrames: 20, stagger: 8, distance: 12, curve: 'outQuart'}),
		texture: {grain: 0.06, vignette: 0.5, grainRate: 8},
	},
	{
		name: 'data',
		description: 'Data journalism: white, serif headlines, charts that draw, orange and blue series',
		dark: false,
		colors: {bg: '#FFFFFF', bg2: '#F3F4F6', surface: '#FFFFFF', text: '#121212', muted: '#6B6B6B', faint: '#C8C8C8', line: '#E1E1E1', accent: '#E4572E', accentText: '#D2461A', accent2: '#2E86AB', highlight: '#FFE08A', positive: '#2A9D8F', negative: '#D1495B', onAccent: '#111111'},
		fonts: {display: 'SourceSerif4', body: 'Inter', mono: 'IBMPlexMono', bangla: 'NotoSerifBengali', serif: 'SourceSerif4'},
		weights: {display: 700, body: 500, strong: 700},
		tracking: {display: -0.02, caps: 0.08},
		caps: false,
		radius: 6,
		motion: motion({distance: 20, curve: 'outCubic', exitFrames: 12}),
		texture: {grain: 0, vignette: 0, grainRate: 6},
	},
	{
		name: 'trailer',
		description: 'Cinematic trailer: black, spaced serif capitals, warm gold, slow fades, light leaks',
		dark: true,
		colors: {bg: '#050505', bg2: '#0D0D0D', surface: '#141414', text: '#F2F2F2', muted: '#8A8A8A', faint: '#333333', line: '#222222', accent: '#E0B354', accentText: '#E0B354', accent2: '#B3261E', highlight: '#E0B354', positive: '#6FBF73', negative: '#B3261E', onAccent: '#050505'},
		fonts: {display: 'Cinzel', body: 'Inter', mono: 'IBMPlexMono', bangla: 'TiroBangla', serif: 'Cinzel'},
		weights: {display: 700, body: 400, strong: 600},
		tracking: {display: 0.06, caps: 0.12},
		caps: true,
		radius: 0,
		motion: motion({enter: 'blur', enterFrames: 36, exitFrames: 24, stagger: 10, distance: 0, curve: 'sine'}),
		texture: {grain: 0.1, vignette: 0.55, grainRate: 12},
	},
	{
		name: 'terminal',
		description: 'Developer and code: GitHub-dark, green prompt, monospace everything, typed text',
		dark: true,
		colors: {bg: '#0D1117', bg2: '#161B22', surface: '#161B22', text: '#E6EDF3', muted: '#8B949E', faint: '#30363D', line: '#21262D', accent: '#3FB950', accentText: '#3FB950', accent2: '#58A6FF', highlight: '#D29922', positive: '#3FB950', negative: '#F85149', onAccent: '#0D1117'},
		fonts: {display: 'JetBrainsMono', body: 'JetBrainsMono', mono: 'JetBrainsMono', bangla: 'NotoSansBengali'},
		weights: {display: 800, body: 400, strong: 700},
		tracking: {display: -0.02, caps: 0.06},
		caps: false,
		radius: 8,
		motion: motion({enter: 'fade', enterFrames: 8, exitFrames: 8, stagger: 3, distance: 0, curve: 'linear'}),
		texture: {grain: 0, vignette: 0, grainRate: 6},
	},
	{
		name: 'brutalist',
		description: 'Brutalist: flat grey, black rules, loud orange and blue, heavy capitals, snapping slides',
		dark: false,
		colors: {bg: '#F2F2F2', bg2: '#FFFFFF', surface: '#FFFFFF', text: '#000000', muted: '#444444', faint: '#9A9A9A', line: '#000000', accent: '#FF4F00', accentText: '#D72000', accent2: '#0047FF', highlight: '#FFEB3B', positive: '#00A651', negative: '#FF1744', onAccent: '#000000'},
		fonts: {display: 'ArchivoBlack', body: 'SpaceGrotesk', mono: 'JetBrainsMono', bangla: 'AnekBangla'},
		weights: {display: 400, body: 500, strong: 700},
		tracking: {display: -0.02, caps: 0.04},
		caps: true,
		radius: 0,
		motion: motion({enter: 'left', enterFrames: 10, exitFrames: 8, stagger: 3, distance: 80, curve: 'snap', spring: 'snappy'}),
		texture: {grain: 0, vignette: 0, grainRate: 6},
	},
	{
		name: 'dhaka',
		description: 'Bangla-first: deep green, red and marigold, Anek Bangla headlines, Noto Sans Bengali text',
		dark: true,
		colors: {bg: '#0E3B2E', bg2: '#134A3A', surface: '#17574A', text: '#F5F1E8', muted: '#B9C4BC', faint: '#3E6B5E', line: '#2A5E50', accent: '#E91738', accentText: '#FF6B72', accent2: '#F6C445', highlight: '#F6C445', positive: '#7CD992', negative: '#FF6B6B', onAccent: '#FFFFFF'},
		fonts: {display: 'AnekBangla', body: 'NotoSansBengali', mono: 'JetBrainsMono', bangla: 'AnekBangla'},
		weights: {display: 800, body: 500, strong: 700},
		tracking: {display: -0.01, caps: 0.04},
		caps: false,
		radius: 18,
		motion: motion({enterFrames: 16, exitFrames: 12, distance: 30}),
		texture: {grain: 0.04, vignette: 0.2, grainRate: 6},
	},
	{
		name: 'fresh',
		description: 'Bright consumer app promo: white, green and coral, geometric sans, springy pops',
		dark: false,
		colors: {bg: '#FFFFFF', bg2: '#F2F7F5', surface: '#FFFFFF', text: '#0B1F17', muted: '#52665D', faint: '#C6D6CF', line: '#E2ECE7', accent: '#00B37E', accentText: '#008755', accent2: '#FF7A59', highlight: '#FFE27A', positive: '#00B37E', negative: '#E5484D', onAccent: '#111111'},
		fonts: {display: 'Outfit', body: 'Figtree', mono: 'JetBrainsMono', bangla: 'AnekBangla'},
		weights: {display: 800, body: 500, strong: 700},
		tracking: {display: -0.035, caps: 0.08},
		caps: false,
		radius: 28,
		motion: motion({enter: 'pop', enterFrames: 14, exitFrames: 10, stagger: 4, distance: 30, curve: 'outBack', spring: 'settle'}),
		texture: {grain: 0, vignette: 0, grainRate: 6},
	},
] as const satisfies readonly ThemeSpec[];

export type ThemeName = (typeof THEME_LIST)[number]['name'];

export const THEMES = Object.fromEntries(THEME_LIST.map((t) => [t.name, t])) as unknown as Record<
	ThemeName,
	ThemeSpec
>;

export const THEME_NAMES = THEME_LIST.map((t) => t.name) as readonly ThemeName[];
